name: Whale Signal Bot

on:
  schedule:
    - cron: '0 9 * * *'  # 한국 시간 18:00 (UTC+9 → UTC 기준 9시)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        USER_ID: ${{ secrets.USER_ID }}
      run: python main.py